// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNGRDfGkhD_yxci8sKvsMpVNFCQzQpEX8',
    appId: '1:100244567190:web:f19966887a3585117a3eb7',
    messagingSenderId: '100244567190',
    projectId: 'ridewise-2bb29',
    authDomain: 'ridewise-2bb29.firebaseapp.com',
    databaseURL: 'https://ridewise-2bb29-default-rtdb.firebaseio.com',
    storageBucket: 'ridewise-2bb29.firebasestorage.app',
    measurementId: 'G-0J0M6JV5XD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkq8WZmBYD_1fONW2AekjGEecsrhC3W50',
    appId: '1:100244567190:android:d07e47f2a1ed1b5d7a3eb7',
    messagingSenderId: '100244567190',
    projectId: 'ridewise-2bb29',
    databaseURL: 'https://ridewise-2bb29-default-rtdb.firebaseio.com',
    storageBucket: 'ridewise-2bb29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeSo6u2Lryg0BcD0GHakMtwBECD7KcC-E',
    appId: '1:100244567190:ios:c071a581e942dde37a3eb7',
    messagingSenderId: '100244567190',
    projectId: 'ridewise-2bb29',
    databaseURL: 'https://ridewise-2bb29-default-rtdb.firebaseio.com',
    storageBucket: 'ridewise-2bb29.firebasestorage.app',
    iosClientId: '100244567190-nnue1s3uaema0f5sirqvgcq7pqolhep9.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeSo6u2Lryg0BcD0GHakMtwBECD7KcC-E',
    appId: '1:100244567190:ios:c071a581e942dde37a3eb7',
    messagingSenderId: '100244567190',
    projectId: 'ridewise-2bb29',
    databaseURL: 'https://ridewise-2bb29-default-rtdb.firebaseio.com',
    storageBucket: 'ridewise-2bb29.firebasestorage.app',
    iosClientId: '100244567190-nnue1s3uaema0f5sirqvgcq7pqolhep9.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );
}
